# Site settings.
title: Jake Bloom
email: jakebloom744@gmail.com
description: I write code and occasionally words too
copyright: '&copy; Jake Bloom 2017'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jake-waratahs.github.io" # the base hostname & protocol for your site
twitter_username: jake1874
github_username:  jake-waratahs
paginate: 5
paginate_path: "/:num"
permalink: '/post/:year/:title/'
# Build settings
markdown: kramdown
include: ['_pages']
gems: [jekyll-paginate]
